import Foundation

// MARK: - Text- und JSON-Ausgabe der chats-Befehle

enum ChatsOutput {
    // MARK: JSON

    /// JSONSerialization + sortedKeys (Vorbild `AgentJobOutput`) — stabile,
    /// diffbare Ausgabe ohne Encoder-Konfigurationstanz.
    static func encodeJSON(_ object: [String: Any]) -> String {
        guard JSONSerialization.isValidJSONObject(object),
              let data = try? JSONSerialization.data(withJSONObject: object, options: [.sortedKeys]) else {
            return "{}"
        }
        return String(decoding: data, as: UTF8.self)
    }

    static func listJSON(
        items: [ChatsAttentionItem],
        counts: [ChatsAttentionCategory: Int],
        selfID: UUID?,
        generatedAt: Date,
        live: Bool = false,
        openTabIDs: Set<UUID> = [],
        pinnedIDs: Set<UUID> = []
    ) -> [String: Any] {
        var countsDict: [String: Any] = [:]
        for category in ChatsAttentionCategory.allCases {
            countsDict[category.rawValue] = counts[category] ?? 0
        }
        return [
            "schemaVersion": 1,
            "generatedAt": iso(generatedAt),
            "live": live,
            "self": selfID?.uuidString ?? NSNull(),
            "counts": countsDict,
            "sessions": items.map { sessionJSON(entry: $0.entry, runtime: $0.runtime, selfID: selfID, live: live, attention: $0,
                                                isOpen: openTabIDs.contains($0.entry.session.id),
                                                isPinned: pinnedIDs.contains($0.entry.session.id)) },
        ]
    }

    static func sessionJSON(
        entry: ChatsSessionEntry,
        runtime: ChatsRuntimeInfo,
        selfID: UUID?,
        live: Bool,
        attention: ChatsAttentionItem? = nil,
        liveStatus: ChatsLiveStatus? = nil,
        isOpen: Bool = false,
        isPinned: Bool = false
    ) -> [String: Any] {
        let session = entry.session
        var runtimeDict: [String: Any] = [
            "status": runtime.status?.rawValue ?? "unknown",
            "source": runtime.source,
        ]
        if let since = runtime.since { runtimeDict["since"] = iso(since) }
        if let revision = runtime.revision { runtimeDict["revision"] = revision }

        var transcriptDict: [String: Any] = ["availability": runtime.availability.rawValue]
        if let path = runtime.transcriptPath { transcriptDict["path"] = path }
        if let size = runtime.transcriptSizeBytes { transcriptDict["sizeBytes"] = size }

        // Capabilities: offline konservativ (keine PTY-Info); mit Live-Merge
        // die autoritativen App-Werte.
        let capabilities: [String: Any] = [
            "canSend": liveStatus?.canSend ?? false,
            "canInterrupt": liveStatus?.canInterrupt ?? false,
            "canOpen": session.status != .archived,
            "isAttachedPTY": liveStatus.map { $0.isAttachedPTY } as Any? ?? NSNull(),
        ]

        var dict: [String: Any] = [
            "id": session.id.uuidString,
            "shortID": shortID(session.id),
            "project": ["name": entry.projectName, "path": entry.projectPath],
            "title": session.title,
            "group": session.groupName ?? NSNull(),
            "provider": session.provider.rawValue,
            "kind": session.effectiveKind.rawValue,
            "status": session.status.rawValue,
            "runtime": runtimeDict,
            "capabilities": capabilities,
            "isSelf": session.id == selfID,
            "isOpen": isOpen,
            "isPinned": isPinned,
            "lastActivityAt": iso(session.lastActivityAt),
            "transcript": transcriptDict,
            "externalSessionID": session.externalSessionID ?? NSNull(),
            "backgroundShortID": session.backgroundShortID ?? NSNull(),
        ]
        if let attention {
            dict["attention"] = ["category": attention.category.rawValue, "rank": attention.rank]
        }
        if let line = tierOneLine(entry: entry, runtime: runtime) {
            dict["lastAssistantLine"] = line
        }
        return dict
    }

    static func detailJSON(entry: ChatsSessionEntry) -> [String: Any] {
        let session = entry.session
        return [
            "model": session.model,
            "reasoningEffort": session.reasoningEffort,
            "createdAt": iso(session.createdAt),
            "lastTurnAt": session.lastTurnAt.map(iso) ?? NSNull(),
            "archivedAt": session.archivedAt.map(iso) ?? NSNull(),
            "titleIsAutoGenerated": session.titleIsAutoGenerated ?? NSNull(),
            "claudeProfileName": session.claudeProfileName ?? NSNull(),
            "claudeBackendModel": session.claudeBackendModel ?? NSNull(),
            "forkSourceSessionID": session.forkSourceSessionID ?? NSNull(),
            "subagentParentSessionID": session.subagentParentSessionID ?? NSNull(),
            "subagentCwd": session.subagentCwd ?? NSNull(),
            "summary": session.summary?.headline ?? NSNull(),
        ]
    }

    // MARK: Text

    static func printTable(items: [ChatsAttentionItem], selfID: UUID?, now: Date,
                           openTabIDs: Set<UUID> = [], pinnedIDs: Set<UUID> = []) {
        guard !items.isEmpty else {
            CLIIO.out("Keine Sessions im Scope. (--all zeigt archivierte und ältere.)")
            return
        }
        CLIIO.out(pad("REF", 10) + pad("PROJEKT/TITEL", 42) + pad("STATUS", 15) + pad("SEIT", 8) + "  FLAGS")
        for item in items {
            let session = item.entry.session
            let name = truncate("\(item.entry.projectName)/\(session.title)", 40)
            let status = item.runtime.status?.rawValue ?? "unknown"
            let since = item.runtime.since.map { relative(from: $0, to: now) } ?? "–"
            CLIIO.out(pad(shortID(session.id), 10) + pad(name, 42) + pad(status, 15) + pad(since, 8) + "  "
                      + flags(session.id, selfID: selfID, openTabIDs: openTabIDs, pinnedIDs: pinnedIDs))
        }
        CLIIO.err("\(items.count) Sessions · ⊙=offener Tab 📌=gepinnt (du)=diese Session")
    }

    /// Flag-Kürzel pro Zeile: offener Tab, gepinnt, Selbst-Markierung.
    private static func flags(_ id: UUID, selfID: UUID?, openTabIDs: Set<UUID>, pinnedIDs: Set<UUID>) -> String {
        var parts: [String] = []
        if openTabIDs.contains(id) { parts.append("⊙") }
        if pinnedIDs.contains(id) { parts.append("📌") }
        if id == selfID { parts.append("(du)") }
        return parts.isEmpty ? "–" : parts.joined(separator: " ")
    }

    static func printBoard(
        items: [ChatsAttentionItem],
        counts: [ChatsAttentionCategory: Int],
        selfID: UUID?,
        showAll: Bool,
        now: Date,
        openTabIDs: Set<UUID> = [],
        pinnedIDs: Set<UUID> = []
    ) {
        let grouped = Dictionary(grouping: items, by: \.category)
        var printedAny = false
        for category in ChatsAttentionCategory.allCases {
            guard let group = grouped[category], !group.isEmpty else { continue }
            if category == .idle && !showAll {
                CLIIO.out(boardHeader(category.boardTitle, count: group.count) + " (--all zeigt sie)")
                continue
            }
            CLIIO.out(boardHeader(category.boardTitle, count: group.count))
            for item in group {
                let session = item.entry.session
                let symbol = statusSymbol(item.runtime.status)
                let name = truncate("\(item.entry.projectName)/\(session.title)", 34)
                let status = item.runtime.status?.rawValue ?? "unknown"
                let since = item.runtime.since.map { "seit \(relative(from: $0, to: now))" } ?? ""
                var marks = ""
                if openTabIDs.contains(session.id) { marks += " ⊙" }
                if pinnedIDs.contains(session.id) { marks += " 📌" }
                if session.id == selfID { marks += " (du)" }
                let estimate = item.runtime.source == "transcriptEstimate" ? " · geschätzt" : ""
                CLIIO.out("\(symbol) \(pad(name, 36))\(pad(status, 15))\(since)\(estimate)\(marks)")
                if category == .needsYou || category == .freshDone,
                   let line = tierOneLine(entry: item.entry, runtime: item.runtime) {
                    CLIIO.out("  „\(line)\"")
                }
            }
            CLIIO.out("")
            printedAny = true
        }
        if !printedAny && items.isEmpty {
            CLIIO.out("Keine Sessions im Scope. (--all zeigt archivierte und ältere.)")
        }
    }

    static func printShow(entry: ChatsSessionEntry, runtime: ChatsRuntimeInfo, selfID: UUID?, now: Date,
                          isOpen: Bool = false, isPinned: Bool = false) {
        let session = entry.session
        var titleMarks = ""
        if isOpen { titleMarks += "  ⊙ offener Tab" }
        if isPinned { titleMarks += "  📌 gepinnt" }
        if session.id == selfID { titleMarks += "  (du)" }
        CLIIO.out("── IDENTITÄT " + String(repeating: "─", count: 40))
        CLIIO.out("Titel        \(session.title)\(titleMarks)")
        CLIIO.out("Projekt      \(entry.projectName)  (\(entry.projectPath))")
        CLIIO.out("Ref          \(shortID(session.id))  ·  \(session.id.uuidString)")
        CLIIO.out("Provider     \(session.provider.rawValue) · \(session.effectiveKind.displayName) · Modell \(session.model)")
        if let group = session.groupName { CLIIO.out("Gruppe       \(group)") }
        if let profile = session.claudeProfileName { CLIIO.out("Profil       \(profile)") }
        CLIIO.out("")
        CLIIO.out("── LAUFZEIT " + String(repeating: "─", count: 41))
        CLIIO.out("Status       \(session.status.rawValue) / runtime: \(runtime.status?.rawValue ?? "unknown") (\(runtime.source))")
        if let since = runtime.since { CLIIO.out("Seit         \(relative(from: since, to: now)) (\(iso(since)))") }
        CLIIO.out("Aktivität    \(relative(from: session.lastActivityAt, to: now)) (\(iso(session.lastActivityAt)))")
        if let lastTurn = session.lastTurnAt { CLIIO.out("Letzter Turn \(relative(from: lastTurn, to: now))") }
        CLIIO.out("")
        CLIIO.out("── TRANSCRIPT " + String(repeating: "─", count: 39))
        CLIIO.out("Verfügbar    \(runtime.availability.rawValue)")
        if let path = runtime.transcriptPath { CLIIO.out("Pfad         \(path)") }
        if let size = runtime.transcriptSizeBytes { CLIIO.out("Größe        \(byteString(size)) (revision \(size))") }
        if let ext = session.externalSessionID { CLIIO.out("Extern-ID    \(ext)") }
        if let short = session.backgroundShortID { CLIIO.out("BG-Short-ID  \(short)") }
    }

    // MARK: Bausteine

    /// Tier-1-Einzeiler: letzte Assistant-Zeile aus dem Transcript-Tail.
    /// Bewusst mit kleinem Tail-Read (16 KB) — läuft pro Board-Zeile.
    static func tierOneLine(entry: ChatsSessionEntry, runtime: ChatsRuntimeInfo) -> String? {
        guard runtime.availability == .available, let path = runtime.transcriptPath else { return nil }
        let fileURL = URL(fileURLWithPath: path)
        let transcript = entry.session.provider == .claude || entry.session.effectiveKind == .backgroundChat
            ? ClaudeTranscriptReader.readTail(fileURL: fileURL, tailBytes: 16_384)
            : CodexTranscriptReader.readTail(fileURL: fileURL, tailBytes: 16_384)
        return ChatsTailFormatter.lastAssistantLine(transcript: transcript)
    }

    static func shortID(_ id: UUID) -> String {
        String(id.uuidString.replacingOccurrences(of: "-", with: "").lowercased().prefix(8))
    }

    static func iso(_ date: Date) -> String {
        isoFormatter.string(from: date)
    }

    static func relative(from date: Date, to now: Date) -> String {
        let seconds = max(0, now.timeIntervalSince(date))
        if seconds < 60 { return "\(Int(seconds)) s" }
        if seconds < 3600 { return "\(Int(seconds / 60)) min" }
        if seconds < 86_400 { return "\(Int(seconds / 3600)) h" }
        return "\(Int(seconds / 86_400)) d"
    }

    static func byteString(_ bytes: Int) -> String {
        if bytes < 1024 { return "\(bytes) B" }
        if bytes < 1_048_576 { return String(format: "%.1f KB", Double(bytes) / 1024) }
        return String(format: "%.1f MB", Double(bytes) / 1_048_576)
    }

    private static func boardHeader(_ title: String, count: Int) -> String {
        let label = "── \(title) "
        let padded = label.padding(toLength: 44, withPad: "─", startingAt: 0)
        return "\(padded) \(count) ──"
    }

    private static func statusSymbol(_ status: AgentSessionRuntimeStatus?) -> String {
        switch status {
        case .awaitingInput: return "◆"
        case .errored: return "✖"
        case .working: return "▶"
        case .idle: return "●"
        case .stopped: return "■"
        case nil: return "·"
        }
    }

    private static func pad(_ text: String, _ width: Int) -> String {
        if text.count >= width { return text + " " }
        return text + String(repeating: " ", count: width - text.count)
    }

    private static func truncate(_ text: String, _ maxChars: Int) -> String {
        if text.count <= maxChars { return text }
        return String(text.prefix(maxChars - 1)) + "…"
    }

    private static let isoFormatter: ISO8601DateFormatter = {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime]
        return formatter
    }()
}
