import Foundation
import XCTest
@testable import WhisperM8

final class AgentSessionAutoNamerTests: XCTestCase {
    func testAgentHeadlessCLIReturnsStdout() async throws {
        let output = try await AgentHeadlessCLI(timeout: 2).run(
            executable: URL(fileURLWithPath: "/bin/echo"),
            arguments: ["hello"],
            environment: [:]
        )

        XCTAssertEqual(output.trimmingCharacters(in: .whitespacesAndNewlines), "hello")
    }

    func testAgentHeadlessCLIReportsNonZeroExit() async throws {
        do {
            _ = try await AgentHeadlessCLI(timeout: 2).run(
                executable: URL(fileURLWithPath: "/bin/sh"),
                arguments: ["-c", "echo nope >&2; exit 7"],
                environment: [:]
            )
            XCTFail("Expected non-zero exit")
        } catch AgentHeadlessCLIError.nonZeroExit(let code, let stderr, _) {
            XCTAssertEqual(code, 7)
            XCTAssertTrue(stderr.contains("nope"))
        }
    }

    func testAgentHeadlessCLITimesOut() async throws {
        do {
            _ = try await AgentHeadlessCLI(timeout: 0.05).run(
                executable: URL(fileURLWithPath: "/bin/sleep"),
                arguments: ["2"],
                environment: [:]
            )
            XCTFail("Expected timeout")
        } catch AgentHeadlessCLIError.timedOut {
            // Expected.
        }
    }

    func testAgentHeadlessCLIHandlesOutputLargerThanPipeBuffer() async throws {
        // Regression Review-Befund 2026-07-19: Ausgaben > 64-KB-Pipe-Puffer
        // liessen den Prozess beim Schreiben blockieren (Read erst im
        // terminationHandler) → Timeout statt Ergebnis.
        let output = try await AgentHeadlessCLI(timeout: 10).run(
            executable: URL(fileURLWithPath: "/bin/sh"),
            arguments: ["-c", "yes a | head -c 300000"],
            environment: [:]
        )
        XCTAssertEqual(output.utf8.count, 300_000)
    }

    func testAgentHeadlessCLIDoesNotHangOnStdinReaders() async throws {
        // stdin ist /dev/null: ein Befehl, der von stdin liest (z. B. ein
        // Bestaetigungs-Prompt), bekommt sofort EOF statt ewig zu warten.
        let output = try await AgentHeadlessCLI(timeout: 5).run(
            executable: URL(fileURLWithPath: "/bin/sh"),
            arguments: ["-c", "cat; echo done"],
            environment: [:]
        )
        XCTAssertEqual(output.trimmingCharacters(in: .whitespacesAndNewlines), "done")
    }

    // MARK: - Auto-Title Flag

    func testCanAutoRenameTitleAllowsLegacyDefaultName() {
        // Legacy-Sessions ohne Flag, aber mit Default-Name → Auto-Rename erlaubt.
        let session = AgentChatSession(
            provider: .claude,
            projectID: UUID(),
            title: "Claude Chat"
        )
        XCTAssertTrue(session.canAutoRenameTitle)
    }

    func testCanAutoRenameTitleBlocksUserSuppliedName() {
        // Wenn der User explizit umbenannt hat, kommt das Flag = false rein.
        var session = AgentChatSession(
            provider: .claude,
            projectID: UUID(),
            title: "My Custom Project Name"
        )
        session.titleIsAutoGenerated = false
        XCTAssertFalse(session.canAutoRenameTitle)
    }

    func testCanAutoRenameTitleAllowsAutoGeneratedReplacement() {
        // Auto-generierter Name darf vom Auto-Namer überschrieben werden
        // (nützlich, falls die Session weiterläuft und sich neu fokussiert).
        var session = AgentChatSession(
            provider: .codex,
            projectID: UUID(),
            title: "Initial auto title"
        )
        session.titleIsAutoGenerated = true
        XCTAssertTrue(session.canAutoRenameTitle)
    }

    func testApplyAutoGeneratedTitleRespectsManualRename() throws {
        let url = makeTempStoreURL()
        defer { try? FileManager.default.removeItem(at: url) }
        let store = AgentSessionStore(fileURL: url)
        let session = try store.createSession(
            provider: .claude,
            projectPath: NSTemporaryDirectory(),
            title: "Claude Chat"
        )
        // User benennt manuell um → Flag = false.
        try store.renameSession(id: session.id, title: "Important Bugfix")
        // Auto-Namer versucht zu schreiben — darf nicht durchkommen.
        try store.applyAutoGeneratedTitle(id: session.id, title: "Generic Auto Name")
        let workspace = store.loadWorkspace()
        let updated = workspace.sessions.first { $0.id == session.id }
        XCTAssertEqual(updated?.title, "Important Bugfix")
        XCTAssertEqual(updated?.titleIsAutoGenerated, false)
    }

    func testApplyAutoGeneratedTitleAcceptsLegacyDefaultName() throws {
        let url = makeTempStoreURL()
        defer { try? FileManager.default.removeItem(at: url) }
        let store = AgentSessionStore(fileURL: url)
        let session = try store.createSession(
            provider: .claude,
            projectPath: NSTemporaryDirectory(),
            title: "Claude Chat"
        )
        try store.applyAutoGeneratedTitle(id: session.id, title: "Login UI Refactor")
        let workspace = store.loadWorkspace()
        let updated = workspace.sessions.first { $0.id == session.id }
        XCTAssertEqual(updated?.title, "Login UI Refactor")
        XCTAssertEqual(updated?.titleIsAutoGenerated, true)
    }

    func testEveryTurnEndReadsNativeClaudeTitleWithoutModelCall() async throws {
        let url = makeTempStoreURL()
        defer { try? FileManager.default.removeItem(at: url) }
        let store = AgentSessionStore(fileURL: url)
        let projectDir = try makeTempProjectDirectory()
        defer { try? FileManager.default.removeItem(at: projectDir) }
        let transcriptURL = projectDir.appendingPathComponent("transcript.jsonl")
        try (#"{"type":"user","message":{"role":"user","content":"refactor my login flow"}}"# + "\n")
            .write(to: transcriptURL, atomically: true, encoding: .utf8)

        var session = try store.createSession(provider: .claude, projectPath: projectDir.path, title: "Claude Chat")
        session.externalSessionID = "11111111-2222-3333-4444-555555555555"
        session.lastTurnAt = Date()  // früher blockte das; jetzt liest jedes Turn-Ende neu
        _ = try store.upsertSession(session)

        let namer = await AgentSessionAutoNamer(
            store: store, isEnabled: { true },
            titleLoader: { session, _ in
                guard let title = NativeSessionTitle.resolve(provider: session.provider, transcriptURL: transcriptURL) else {
                    throw AgentTitleGeneratorError.emptyExcerpt
                }
                return title
            }
        )
        func turnEnd(_ step: String) async {
            let current = store.loadWorkspace().sessions.first { $0.id == session.id }!
            let done = expectation(description: step)
            await namer.handleTurnFinished(session: current, cwd: projectDir.path) { _ in done.fulfill() }
            await fulfillment(of: [done], timeout: 5)
        }
        await turnEnd("erster Prompt")
        XCTAssertEqual(store.loadWorkspace().sessions.first { $0.id == session.id }?.title, "refactor my login flow",
                       "Ohne Claude-Titel gilt der erste Prompt")

        // Claude schreibt den generierten Titel nach; ein späteres /rename gewinnt.
        let handle = try FileHandle(forWritingTo: transcriptURL)
        try handle.seekToEnd()
        try handle.write(contentsOf: Data(#"{"type":"ai-title","aiTitle":"Login Flow Refactor","sessionId":"x"}"#.utf8 + [10]))
        await turnEnd("ai-title")
        XCTAssertEqual(store.loadWorkspace().sessions.first { $0.id == session.id }?.title, "Login Flow Refactor")
        try handle.write(contentsOf: Data(#"{"type":"custom-title","customTitle":"auth-refactor","sessionId":"x"}"#.utf8 + [10]))
        try handle.close()
        await turnEnd("custom-title")
        let updated = store.loadWorkspace().sessions.first { $0.id == session.id }
        XCTAssertEqual(updated?.title, "auth-refactor")
        XCTAssertEqual(updated?.titleIsAutoGenerated, true, "Nativer Titel bleibt automatisch, also aufhebbar")
    }

    func testForceGenerateTitleStillRespectsManualRename() async throws {
        // canAutoRenameTitle == false (User hat manuell umbenannt) → force darf NICHT überschreiben.
        let url = makeTempStoreURL()
        defer { try? FileManager.default.removeItem(at: url) }
        let store = AgentSessionStore(fileURL: url)
        var session = try store.createSession(
            provider: .claude,
            projectPath: NSTemporaryDirectory(),
            title: "Manual Important Name"
        )
        session.titleIsAutoGenerated = false  // wie nach manuellem Rename
        session.externalSessionID = "abc-123"
        _ = try store.upsertSession(session)

        let namer = await AgentSessionAutoNamer(store: store, titleLoader: { _, _ in "Should Never Be Set" })
        let expectation = expectation(description: "force call returns or skips")
        expectation.isInverted = true
        await namer.forceGenerateTitle(session: session, cwd: NSTemporaryDirectory()) { _ in
            expectation.fulfill()
        }
        await fulfillment(of: [expectation], timeout: 1)

        let snap = store.loadWorkspace().sessions.first { $0.id == session.id }
        XCTAssertEqual(snap?.title, "Manual Important Name")
    }

    func testRecordTurnEndedSetsLastTurnAt() throws {
        let url = makeTempStoreURL()
        defer { try? FileManager.default.removeItem(at: url) }
        let store = AgentSessionStore(fileURL: url)
        let session = try store.createSession(
            provider: .claude,
            projectPath: NSTemporaryDirectory(),
            title: "Claude Chat"
        )
        let timestamp = Date(timeIntervalSinceReferenceDate: 1_000_000)
        try store.recordTurnEnded(id: session.id, at: timestamp)
        let workspace = store.loadWorkspace()
        let updated = workspace.sessions.first { $0.id == session.id }
        XCTAssertEqual(updated?.lastTurnAt, timestamp)
    }

    // MARK: - P0.4a: Hilfsläufe erzeugen keine importierbaren Sessions

    func testRetryAfterUnknownOptionStripsOnlyTheRejectedFlag() {
        let args = ["-p", "prompt", "--output-format", "text", "--no-session-persistence"]

        let retry = AgentTitleGenerator.retryArgumentsAfterUnknownOption(
            arguments: args,
            stderr: "error: unknown option '--no-session-persistence'"
        )
        XCTAssertEqual(retry, ["-p", "prompt", "--output-format", "text"],
                       "ältere CLI: genau das abgelehnte Flag entfernen")

        XCTAssertNil(AgentTitleGenerator.retryArgumentsAfterUnknownOption(
            arguments: args,
            stderr: "some other failure"
        ), "fremde Fehler lösen keinen Retry aus")

        XCTAssertNil(AgentTitleGenerator.retryArgumentsAfterUnknownOption(
            arguments: ["-p", "prompt"],
            stderr: "error: unknown option '--no-session-persistence'"
        ), "ohne gesetztes Flag kein Retry (Endlosschleifen-Schutz)")
    }

    func testHeadlessCLIRunsInGivenWorkingDirectory() async throws {
        let scratch = FileManager.default.temporaryDirectory
            .appendingPathComponent("wm8-headless-cwd-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: scratch, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: scratch) }

        let stdout = try await AgentHeadlessCLI(timeout: 10).run(
            executable: URL(fileURLWithPath: "/bin/pwd"),
            arguments: [],
            environment: ["PATH": "/usr/bin:/bin"],
            workingDirectory: scratch
        )
        XCTAssertEqual(
            URL(fileURLWithPath: stdout.trimmingCharacters(in: .whitespacesAndNewlines))
                .resolvingSymlinksInPath().path,
            scratch.resolvingSymlinksInPath().path,
            "Hilfslauf läuft im Scratch-cwd, nicht im App-cwd"
        )
    }
}
