import Foundation
import XCTest
@testable import WhisperM8

final class AgentSessionAutoNamerTests: XCTestCase {
    // MARK: - Title Generator Cleanup

    func testTitleGeneratorCleanupStripsQuotesAndPunctuation() {
        XCTAssertEqual(AgentTitleGenerator.cleanTitle("\"Refactor login UI\""), "Refactor login UI")
        XCTAssertEqual(AgentTitleGenerator.cleanTitle("Refactor login UI."), "Refactor login UI")
        XCTAssertEqual(AgentTitleGenerator.cleanTitle("Title: Database Migration!"), "Database Migration")
    }

    func testTitleGeneratorCleanupTakesFirstLineOnly() {
        let raw = "Refactor login UI\nSome explanation goes here"
        XCTAssertEqual(AgentTitleGenerator.cleanTitle(raw), "Refactor login UI")
    }

    func testTitleGeneratorCleanupCapsLength() {
        let long = String(repeating: "A", count: 120)
        let cleaned = AgentTitleGenerator.cleanTitle(long)
        XCTAssertLessThanOrEqual(cleaned.count, 60)
    }

    func testAgentHeadlessCLIReturnsStdout() async throws {
        let output = try await AgentHeadlessCLI(timeout: 2).run(
            executable: URL(fileURLWithPath: "/bin/echo"),
            arguments: ["hello"],
            environment: [:]
        )

        XCTAssertEqual(output.trimmingCharacters(in: .whitespacesAndNewlines), "hello")
    }

    func testAgentHeadlessCLIReportsNonZeroExit() async throws {
        do {
            _ = try await AgentHeadlessCLI(timeout: 2).run(
                executable: URL(fileURLWithPath: "/bin/sh"),
                arguments: ["-c", "echo nope >&2; exit 7"],
                environment: [:]
            )
            XCTFail("Expected non-zero exit")
        } catch AgentHeadlessCLIError.nonZeroExit(let code, let stderr) {
            XCTAssertEqual(code, 7)
            XCTAssertTrue(stderr.contains("nope"))
        }
    }

    func testAgentHeadlessCLITimesOut() async throws {
        do {
            _ = try await AgentHeadlessCLI(timeout: 0.05).run(
                executable: URL(fileURLWithPath: "/bin/sleep"),
                arguments: ["2"],
                environment: [:]
            )
            XCTFail("Expected timeout")
        } catch AgentHeadlessCLIError.timedOut {
            // Expected.
        }
    }

    func testAgentHeadlessCLIHandlesOutputLargerThanPipeBuffer() async throws {
        // Regression Review-Befund 2026-07-19: Ausgaben > 64-KB-Pipe-Puffer
        // liessen den Prozess beim Schreiben blockieren (Read erst im
        // terminationHandler) → Timeout statt Ergebnis.
        let output = try await AgentHeadlessCLI(timeout: 10).run(
            executable: URL(fileURLWithPath: "/bin/sh"),
            arguments: ["-c", "yes a | head -c 300000"],
            environment: [:]
        )
        XCTAssertEqual(output.utf8.count, 300_000)
    }

    func testAgentHeadlessCLIDoesNotHangOnStdinReaders() async throws {
        // stdin ist /dev/null: ein Befehl, der von stdin liest (z. B. ein
        // Bestaetigungs-Prompt), bekommt sofort EOF statt ewig zu warten.
        let output = try await AgentHeadlessCLI(timeout: 5).run(
            executable: URL(fileURLWithPath: "/bin/sh"),
            arguments: ["-c", "cat; echo done"],
            environment: [:]
        )
        XCTAssertEqual(output.trimmingCharacters(in: .whitespacesAndNewlines), "done")
    }

    // MARK: - Auto-Title Flag

    func testCanAutoRenameTitleAllowsLegacyDefaultName() {
        // Legacy-Sessions ohne Flag, aber mit Default-Name → Auto-Rename erlaubt.
        let session = AgentChatSession(
            provider: .claude,
            projectID: UUID(),
            title: "Claude Chat"
        )
        XCTAssertTrue(session.canAutoRenameTitle)
    }

    func testCanAutoRenameTitleBlocksUserSuppliedName() {
        // Wenn der User explizit umbenannt hat, kommt das Flag = false rein.
        var session = AgentChatSession(
            provider: .claude,
            projectID: UUID(),
            title: "My Custom Project Name"
        )
        session.titleIsAutoGenerated = false
        XCTAssertFalse(session.canAutoRenameTitle)
    }

    func testCanAutoRenameTitleAllowsAutoGeneratedReplacement() {
        // Auto-generierter Name darf vom Auto-Namer überschrieben werden
        // (nützlich, falls die Session weiterläuft und sich neu fokussiert).
        var session = AgentChatSession(
            provider: .codex,
            projectID: UUID(),
            title: "Initial auto title"
        )
        session.titleIsAutoGenerated = true
        XCTAssertTrue(session.canAutoRenameTitle)
    }

    func testApplyAutoGeneratedTitleRespectsManualRename() throws {
        let url = makeTempStoreURL()
        defer { try? FileManager.default.removeItem(at: url) }
        let store = AgentSessionStore(fileURL: url)
        let session = try store.createSession(
            provider: .claude,
            projectPath: NSTemporaryDirectory(),
            title: "Claude Chat"
        )
        // User benennt manuell um → Flag = false.
        try store.renameSession(id: session.id, title: "Important Bugfix")
        // Auto-Namer versucht zu schreiben — darf nicht durchkommen.
        try store.applyAutoGeneratedTitle(id: session.id, title: "Generic Auto Name")
        let workspace = store.loadWorkspace()
        let updated = workspace.sessions.first { $0.id == session.id }
        XCTAssertEqual(updated?.title, "Important Bugfix")
        XCTAssertEqual(updated?.titleIsAutoGenerated, false)
    }

    func testApplyAutoGeneratedTitleAcceptsLegacyDefaultName() throws {
        let url = makeTempStoreURL()
        defer { try? FileManager.default.removeItem(at: url) }
        let store = AgentSessionStore(fileURL: url)
        let session = try store.createSession(
            provider: .claude,
            projectPath: NSTemporaryDirectory(),
            title: "Claude Chat"
        )
        try store.applyAutoGeneratedTitle(id: session.id, title: "Login UI Refactor")
        let workspace = store.loadWorkspace()
        let updated = workspace.sessions.first { $0.id == session.id }
        XCTAssertEqual(updated?.title, "Login UI Refactor")
        XCTAssertEqual(updated?.titleIsAutoGenerated, true)
    }

    func testForceGenerateTitleBypassesLastTurnAtAndAttemptedSet() async throws {
        // Force-Pfad: gescannte alte Session hat schon `lastTurnAt` und der
        // Namer hat sie ggf. in `alreadyAttempted`. Beides muss `forceGenerateTitle`
        // ignorieren — solange `canAutoRenameTitle == true` bleibt.
        let url = makeTempStoreURL()
        defer { try? FileManager.default.removeItem(at: url) }
        let store = AgentSessionStore(fileURL: url)

        // Echtes Claude-Transcript anlegen, damit der Locator + Excerpt-Builder Daten sehen.
        let projectDir = try makeTempProjectDirectory()
        defer { try? FileManager.default.removeItem(at: projectDir) }
        let externalSessionID = "11111111-2222-3333-4444-555555555555"
        let claudeBase = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".claude")
            .appendingPathComponent("projects")
            .appendingPathComponent(AgentTranscriptLocator.encodeClaudeCwd(projectDir.path))
        try? FileManager.default.createDirectory(at: claudeBase, withIntermediateDirectories: true)
        let transcriptURL = claudeBase.appendingPathComponent("\(externalSessionID).jsonl")
        defer { try? FileManager.default.removeItem(at: transcriptURL) }
        let transcript = #"""
        {"type":"user","message":{"role":"user","content":"refactor my login flow"}}
        {"type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"Here is a plan."}],"stop_reason":"end_turn"}}
        """#
        try transcript.write(to: transcriptURL, atomically: true, encoding: .utf8)

        var session = try store.createSession(
            provider: .claude,
            projectPath: projectDir.path,
            title: "Claude Chat"
        )
        session.externalSessionID = externalSessionID
        session.lastTurnAt = Date()  // simuliert Resume-Session, blockt normalerweise Auto-Naming
        _ = try store.upsertSession(session)

        let stub = AgentTitleGenerator(
            executableResolver: { _ in "/usr/bin/true" },
            runner: { _, _, _ in "Login Flow Refactor" }
        )
        let namer = await AgentSessionAutoNamer(store: store, titleGenerator: stub)
        await namer.resetAttemptTracking()
        // Auch wenn sie zuvor schon mal blockiert war, force soll es trotzdem tun.
        await namer.handleTurnFinished(session: session, cwd: projectDir.path)

        let snapshotAfterRegular = store.loadWorkspace().sessions.first { $0.id == session.id }
        XCTAssertEqual(snapshotAfterRegular?.title, "Claude Chat",
                       "handleTurnFinished blockt erwartungsgemäß bei lastTurnAt != nil")

        // Force-Pfad: blocking flags werden ignoriert, Title wird gesetzt.
        let expectation = expectation(description: "force-naming completes")
        await namer.forceGenerateTitle(session: session, cwd: projectDir.path) { result in
            if case .success = result { expectation.fulfill() }
        }
        await fulfillment(of: [expectation], timeout: 5)

        let updated = store.loadWorkspace().sessions.first { $0.id == session.id }
        XCTAssertEqual(updated?.title, "Login Flow Refactor")
        XCTAssertEqual(updated?.titleIsAutoGenerated, true)
    }

    func testForceGenerateTitleStillRespectsManualRename() async throws {
        // canAutoRenameTitle == false (User hat manuell umbenannt) → force darf NICHT überschreiben.
        let url = makeTempStoreURL()
        defer { try? FileManager.default.removeItem(at: url) }
        let store = AgentSessionStore(fileURL: url)
        var session = try store.createSession(
            provider: .claude,
            projectPath: NSTemporaryDirectory(),
            title: "Manual Important Name"
        )
        session.titleIsAutoGenerated = false  // wie nach manuellem Rename
        session.externalSessionID = "abc-123"
        _ = try store.upsertSession(session)

        let stub = AgentTitleGenerator(
            executableResolver: { _ in "/usr/bin/true" },
            runner: { _, _, _ in "Should Never Be Set" }
        )
        let namer = await AgentSessionAutoNamer(store: store, titleGenerator: stub)
        let expectation = expectation(description: "force call returns or skips")
        expectation.isInverted = true
        await namer.forceGenerateTitle(session: session, cwd: NSTemporaryDirectory()) { _ in
            expectation.fulfill()
        }
        await fulfillment(of: [expectation], timeout: 1)

        let snap = store.loadWorkspace().sessions.first { $0.id == session.id }
        XCTAssertEqual(snap?.title, "Manual Important Name")
    }

    func testRecordTurnEndedSetsLastTurnAt() throws {
        let url = makeTempStoreURL()
        defer { try? FileManager.default.removeItem(at: url) }
        let store = AgentSessionStore(fileURL: url)
        let session = try store.createSession(
            provider: .claude,
            projectPath: NSTemporaryDirectory(),
            title: "Claude Chat"
        )
        let timestamp = Date(timeIntervalSinceReferenceDate: 1_000_000)
        try store.recordTurnEnded(id: session.id, at: timestamp)
        let workspace = store.loadWorkspace()
        let updated = workspace.sessions.first { $0.id == session.id }
        XCTAssertEqual(updated?.lastTurnAt, timestamp)
    }
}
