import XCTest
@testable import WhisperM8

// MARK: - Normalisierung + Query-Übersetzung

final class ChatSearchNormalizerTests: XCTestCase {
    func testNormalizeFoldsDiacriticsCaseAndEszett() {
        XCTAssertEqual(ChatSearchNormalizer.normalize("Größen"), "grossen")
        XCTAssertEqual(ChatSearchNormalizer.normalize("MÜNCHEN"), "munchen")
        XCTAssertEqual(ChatSearchNormalizer.normalize("Lead-Kategorisierung"), "lead-kategorisierung")
        XCTAssertEqual(ChatSearchNormalizer.normalize("Straße"), "strasse")
    }

    func testNormalizeIsStableForPlainAscii() {
        XCTAssertEqual(ChatSearchNormalizer.normalize("make webhook"), "make webhook")
    }

    func testFTSExpressionJoinsWordsWithAnd() {
        XCTAssertEqual(
            ChatSearchNormalizer.ftsExpression(for: "Lead Kategorisierung"),
            "\"lead\" AND \"kategorisierung\""
        )
    }

    func testFTSExpressionNeutralizesSyntaxCharacters() {
        // Bindestriche, Sternchen und Doppelpunkte sind FTS5-Syntax — roh
        // durchgereicht bricht die Query mit einem SQL-Fehler ab.
        let expression = ChatSearchNormalizer.ftsExpression(for: "Lead-Kategorisierung: NEAR* x")
        XCTAssertEqual(expression, "\"lead\" AND \"kategorisierung\" AND \"near\" AND \"x\"")
    }

    func testFTSExpressionKeepsQuotedPhraseTogether() {
        XCTAssertEqual(
            ChatSearchNormalizer.ftsExpression(for: "\"nachbau in make\""),
            "\"nachbau in make\""
        )
    }

    func testFTSExpressionEscapesEmbeddedQuotesAndRejectsEmptyInput() {
        XCTAssertEqual(ChatSearchNormalizer.ftsExpression(for: "a\"b"), "\"a\" AND \"b\"")
        XCTAssertNil(ChatSearchNormalizer.ftsExpression(for: "   "))
        XCTAssertNil(ChatSearchNormalizer.ftsExpression(for: "--- *** "))
    }
}

// MARK: - Harness-Split

final class HarnessTextSplitterTests: XCTestCase {
    func testPlainUserTextStaysHuman() {
        XCTAssertEqual(
            HarnessTextSplitter.split("Finde den Chat zur Lead-Kategorisierung"),
            [.init(text: "Finde den Chat zur Lead-Kategorisierung", kind: .humanUser)]
        )
    }

    func testSystemReminderIsSplitOutOfUserMessage() {
        let raw = "Echte Frage vom Nutzer\n<system-reminder>Interner Hinweis über Make</system-reminder>\nUnd noch ein Satz"
        let segments = HarnessTextSplitter.split(raw)
        XCTAssertEqual(segments.count, 3)
        XCTAssertEqual(segments[0], .init(text: "Echte Frage vom Nutzer", kind: .humanUser))
        XCTAssertEqual(segments[1], .init(text: "Interner Hinweis über Make", kind: .system))
        XCTAssertEqual(segments[2], .init(text: "Und noch ein Satz", kind: .humanUser))
    }

    func testUnclosedTagIsTreatedAsHarnessNotUserText() {
        let segments = HarnessTextSplitter.split("Frage\n<system-reminder>abgeschnitten…")
        XCTAssertEqual(segments.map(\.kind), [.humanUser, .system])
    }

    func testFullLineHarnessMarkersAreNeverHumanText() {
        for marker in ["[Request interrupted by user]",
                       "[via whisperm8 chats · von extern] mach X",
                       "Caveat: The messages below were generated by the user while running local commands."] {
            XCTAssertEqual(HarnessTextSplitter.split(marker).map(\.kind), [.system], marker)
        }
    }

    func testEmptyInputYieldsNothing() {
        XCTAssertTrue(HarnessTextSplitter.split("   \n ").isEmpty)
    }
}

// MARK: - Extraktion

final class ChatSearchContentExtractorTests: XCTestCase {
    private func spans(_ line: String, _ provider: AgentProvider) -> [ChatSearchSpan] {
        ChatSearchContentExtractor.spans(line: line, provider: provider, byteOffset: 100, lineNumber: 7)
    }

    func testClaudeUserTextIsHumanAndCarriesOrigin() {
        let line = #"{"type":"user","timestamp":"2026-07-20T12:07:00.000Z","message":{"content":"Lead-Kategorisierung über Make"}}"#
        let result = spans(line, .claude)
        XCTAssertEqual(result.count, 1)
        XCTAssertEqual(result[0].kind, .humanUser)
        XCTAssertEqual(result[0].role, .user)
        XCTAssertEqual(result[0].text, "Lead-Kategorisierung über Make")
        XCTAssertEqual(result[0].byteOffset, 100)
        XCTAssertEqual(result[0].lineNumber, 7)
        XCTAssertNotNil(result[0].timestamp)
    }

    func testClaudeToolResultIsNotUserText() {
        let line = #"{"type":"user","message":{"content":[{"type":"tool_result","content":"Make webhook 200 OK"}]}}"#
        let result = spans(line, .claude)
        XCTAssertEqual(result.map(\.kind), [.toolResult])
    }

    func testClaudeAssistantSplitsNarrativeToolUseAndThinking() {
        let line = #"""
        {"type":"assistant","message":{"content":[{"type":"text","text":"Ich erkläre den Flow"},{"type":"tool_use","name":"Bash","input":{"command":"ls"}},{"type":"thinking","thinking":"überlege"}]}}
        """#
        let result = spans(line, .claude)
        XCTAssertEqual(result.map(\.kind), [.assistantNarrative, .toolCall, .thinking])
        XCTAssertEqual(result[0].text, "Ich erkläre den Flow")
        XCTAssertTrue(result[1].text.contains("Bash"))
        XCTAssertEqual(result.map(\.blockIndex), [0, 1, 2], "Blockindex zählt innerhalb der Zeile")
    }

    func testClaudeUserMessageWithReminderYieldsBothClasses() {
        let line = #"{"type":"user","message":{"content":[{"type":"text","text":"Echte Frage<system-reminder>Rauschen</system-reminder>"}]}}"#
        let result = spans(line, .claude)
        XCTAssertEqual(result.map(\.kind), [.humanUser, .system])
        XCTAssertEqual(result[0].text, "Echte Frage")
    }

    func testCodexEventMessagesMapToConversationalKinds() {
        let user = #"{"type":"event_msg","payload":{"type":"user_message","message":"Frage an Codex"}}"#
        let agent = #"{"type":"event_msg","payload":{"type":"agent_message","message":"Antwort von Codex"}}"#
        XCTAssertEqual(spans(user, .codex).map(\.kind), [.humanUser])
        XCTAssertEqual(spans(agent, .codex).map(\.kind), [.assistantNarrative])
    }

    func testCodexResponseItemMessageIsSkippedAsDuplicate() {
        // Diese Zeilen duplizieren die event_msg-Texte — würden sie indexiert,
        // erschiene jeder Codex-Chat doppelt in der Trefferliste.
        let line = #"{"type":"response_item","payload":{"type":"message","role":"user","content":[{"type":"input_text","text":"Frage an Codex"}]}}"#
        XCTAssertTrue(spans(line, .codex).isEmpty)
    }

    func testCodexToolCallsAndOutputsAreClassified() {
        let call = #"{"type":"response_item","payload":{"type":"function_call","name":"shell","arguments":"{\"cmd\":\"ls\"}"}}"#
        let output = #"{"type":"response_item","payload":{"type":"function_call_output","output":"Process exited with code 0"}}"#
        XCTAssertEqual(spans(call, .codex).map(\.kind), [.toolCall])
        XCTAssertEqual(spans(output, .codex).map(\.kind), [.toolResult])
    }

    func testMalformedAndIrrelevantLinesYieldNothing() {
        XCTAssertTrue(spans("{kaputt", .claude).isEmpty)
        XCTAssertTrue(spans("", .claude).isEmpty)
        XCTAssertTrue(spans(#"{"type":"file-history-snapshot"}"#, .claude).isEmpty)
        XCTAssertTrue(spans(#"{"type":"event_msg","payload":{"type":"token_count"}}"#, .codex).isEmpty)
    }

    func testEmptyTextBlocksAreDropped() {
        let line = #"{"type":"assistant","message":{"content":[{"type":"text","text":"   "}]}}"#
        XCTAssertTrue(spans(line, .claude).isEmpty)
    }

    func testHugeToolOutputIsCappedButConversationalTextIsNot() {
        let huge = String(repeating: "x", count: ChatSearchContentExtractor.nonConversationalTextCap + 5_000)
        let toolLine = #"{"type":"user","message":{"content":[{"type":"tool_result","content":"\#(huge)"}]}}"#
        let capped = spans(toolLine, .claude)
        XCTAssertEqual(capped.count, 1)
        XCTAssertEqual(capped[0].text.count, ChatSearchContentExtractor.nonConversationalTextCap)

        let userLine = #"{"type":"user","message":{"content":"\#(huge)"}}"#
        XCTAssertEqual(spans(userLine, .claude)[0].text.count, huge.count, "Gesprächstext wird nie gekürzt")
    }
}

// MARK: - Datenbank + Nebenläufigkeit

final class ChatSearchDatabaseTests: XCTestCase {
    private var directory: URL!

    override func setUpWithError() throws {
        directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("chat-search-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
    }

    override func tearDownWithError() throws {
        try? FileManager.default.removeItem(at: directory)
    }

    private func makeDatabase() throws -> ChatSearchDatabase {
        try ChatSearchDatabase(fileURL: directory.appendingPathComponent("index.sqlite"))
    }

    func testMigrateCreatesSchemaInWALModeAndIsIdempotent() throws {
        let database = try makeDatabase()
        XCTAssertFalse(try database.migrate(), "frischer Index wird nicht verworfen")
        XCTAssertFalse(try database.migrate(), "zweiter Lauf ist ein No-op")

        let mode = try database.prepare("PRAGMA journal_mode;") { statement -> String? in
            _ = try statement.next()
            return statement.text(at: 0)
        }
        XCTAssertEqual(mode?.lowercased(), "wal")
        XCTAssertEqual(try database.meta(for: "schemaVersion"), String(ChatSearchDatabase.schemaVersion))
    }

    func testSchemaVersionMismatchDropsDerivedContent() throws {
        let database = try makeDatabase()
        try database.migrate()
        try database.execute("""
            INSERT INTO transcripts(id, provider, path) VALUES (1, 'claude', '/tmp/a.jsonl');
            INSERT INTO messages(id, transcript_id, byte_offset, line_number, block_index, role, kind, text)
            VALUES (1, 1, 0, 1, 0, 'user', 'humanUser', 'hallo');
            """)
        try database.setMeta("schemaVersion", "0")

        XCTAssertTrue(try database.migrate(), "veralteter Index wird verworfen")
        let count = try database.prepare("SELECT count(*) FROM messages") { statement -> Int64 in
            _ = try statement.next()
            return statement.int(at: 0)
        }
        XCTAssertEqual(count, 0)
        XCTAssertEqual(try database.meta(for: "schemaVersion"), String(ChatSearchDatabase.schemaVersion))
    }

    func testNormalizerVersionMismatchAlsoForcesRebuild() throws {
        let database = try makeDatabase()
        try database.migrate()
        try database.setMeta("normalizerVersion", "-1")
        XCTAssertTrue(try database.migrate(), "Normalisierungswechsel macht den Index unbrauchbar")
    }

    func testFTSRoundTripFindsNormalizedGermanTextAndSupportsDelete() throws {
        let database = try makeDatabase()
        try database.migrate()
        try database.execute("INSERT INTO transcripts(id, provider, path) VALUES (1, 'claude', '/tmp/a.jsonl');")

        try database.writeTransaction {
            for (rowid, text) in [(1, "Die Größen-Kategorisierung läuft über Make"), (2, "Etwas völlig anderes")] {
                try database.prepare("""
                    INSERT INTO messages(id, transcript_id, byte_offset, line_number, block_index, role, kind, text)
                    VALUES (?, 1, 0, ?, 0, 'user', 'humanUser', ?)
                    """) { statement in
                    try statement.bind(int: Int64(rowid), at: 1)
                    try statement.bind(int: Int64(rowid), at: 2)
                    try statement.bind(text: text, at: 3)
                    try statement.run()
                }
                try database.prepare("INSERT INTO messages_fts(rowid, norm) VALUES (?, ?)") { statement in
                    try statement.bind(int: Int64(rowid), at: 1)
                    try statement.bind(text: ChatSearchNormalizer.normalize(text), at: 2)
                    try statement.run()
                }
            }
        }

        func matches(_ query: String) throws -> [String] {
            let expression = try XCTUnwrap(ChatSearchNormalizer.ftsExpression(for: query))
            return try database.prepare("""
                SELECT m.text FROM messages_fts f JOIN messages m ON m.id = f.rowid
                WHERE messages_fts MATCH ? ORDER BY bm25(messages_fts)
                """) { statement in
                try statement.bind(text: expression, at: 1)
                var found: [String] = []
                while try statement.next() { found.append(statement.text(at: 0) ?? "") }
                return found
            }
        }

        // Der Kernfall: getippt wird ohne Umlaute, gefunden wird mit.
        XCTAssertEqual(try matches("grossen").count, 1)
        XCTAssertEqual(try matches("Größen").count, 1)
        XCTAssertTrue(try matches("grossen").first?.contains("Größen-Kategorisierung") ?? false,
                      "Snippet-Quelle bleibt der Originaltext")
        XCTAssertEqual(try matches("kategorisierung make").count, 1, "Wörter werden UND-verknüpft")
        XCTAssertTrue(try matches("kategorisierung banane").isEmpty)
        // Syntax-Zeichen dürfen nicht als FTS-Operatoren wirken.
        XCTAssertEqual(try matches("Größen-Kategorisierung").count, 1)

        try database.execute("DELETE FROM messages_fts WHERE rowid = 1;")
        XCTAssertTrue(try matches("grossen").isEmpty, "contentless_delete entfernt den Eintrag wirklich")
    }

    func testWriterLockIsExclusiveAndReleasedOnDeinit() throws {
        let url = directory.appendingPathComponent("index.sqlite")
        var first: ChatSearchWriterLock? = ChatSearchWriterLock(fileURL: url)
        XCTAssertNotNil(first, "erster Indexlauf bekommt den Lock")
        XCTAssertNil(ChatSearchWriterLock(fileURL: url), "zweiter Prozess wartet nicht, er überspringt")

        first = nil
        let third = ChatSearchWriterLock(fileURL: url)
        XCTAssertNotNil(third, "nach Freigabe wieder verfügbar")
        _ = third
    }

    func testReadersAreNotBlockedByAnOpenWriteTransaction() throws {
        let url = directory.appendingPathComponent("index.sqlite")
        let writer = try ChatSearchDatabase(fileURL: url)
        try writer.migrate()
        try writer.execute("INSERT INTO transcripts(id, provider, path) VALUES (1, 'claude', '/tmp/a.jsonl');")

        // WAL-Kernversprechen: die CLI darf lesen, während die App schreibt.
        let reader = try ChatSearchDatabase(fileURL: url)
        try writer.execute("BEGIN IMMEDIATE;")
        try writer.execute("INSERT INTO transcripts(id, provider, path) VALUES (2, 'codex', '/tmp/b.jsonl');")

        let visible = try reader.prepare("SELECT count(*) FROM transcripts") { statement -> Int64 in
            _ = try statement.next()
            return statement.int(at: 0)
        }
        XCTAssertEqual(visible, 1, "Leser sieht den committeten Stand, ohne zu blockieren")

        try writer.execute("COMMIT;")
        let afterCommit = try reader.prepare("SELECT count(*) FROM transcripts") { statement -> Int64 in
            _ = try statement.next()
            return statement.int(at: 0)
        }
        XCTAssertEqual(afterCommit, 2)
    }

    func testWriteTransactionRollsBackOnError() throws {
        let database = try makeDatabase()
        try database.migrate()
        struct Boom: Error {}

        XCTAssertThrowsError(try database.writeTransaction {
            try database.execute("INSERT INTO transcripts(id, provider, path) VALUES (1, 'claude', '/tmp/a.jsonl');")
            throw Boom()
        })

        let count = try database.prepare("SELECT count(*) FROM transcripts") { statement -> Int64 in
            _ = try statement.next()
            return statement.int(at: 0)
        }
        XCTAssertEqual(count, 0, "fehlgeschlagener Lauf hinterlässt keine Teildaten")
    }
}
