import XCTest
@testable import WhisperM8

// MARK: - Fixtures

private func makeEntry(
    title: String,
    projectName: String = "whisperm8",
    projectPath: String = "/Users/tester/repos/whisperm8",
    id: UUID = UUID(),
    status: AgentChatStatus = .running,
    groupName: String? = nil,
    lastActivityAt: Date = Date(),
    lastTurnAt: Date? = nil,
    kind: AgentSessionKind? = nil,
    provider: AgentProvider = .claude
) -> ChatsSessionEntry {
    ChatsSessionEntry(
        session: AgentChatSession(
            id: id,
            provider: provider,
            projectID: UUID(),
            title: title,
            status: status,
            groupName: groupName,
            lastActivityAt: lastActivityAt,
            titleIsAutoGenerated: nil,
            lastTurnAt: lastTurnAt,
            kind: kind
        ),
        projectName: projectName,
        projectPath: projectPath
    )
}

// MARK: - SessionRefResolver

final class SessionRefResolverTests: XCTestCase {
    func testFullUUIDMatchesExactly() {
        let id = UUID()
        let entries = [makeEntry(title: "a", id: id), makeEntry(title: "b")]
        let result = SessionRefResolver.resolve(ref: id.uuidString.lowercased(), entries: entries, selfID: nil)
        XCTAssertEqual(try? result.get().session.id, id)
    }

    func testHexPrefixMatchesUnique() {
        let id = UUID(uuidString: "CAFEBABE-0000-4000-8000-000000000001")!
        let entries = [makeEntry(title: "cafebabe-titel-falle", id: id), makeEntry(title: "other")]
        // „cafebabe" ist 8 Hex-Zeichen → UUID-Präfix gewinnt vor dem Titel-Match.
        let result = SessionRefResolver.resolve(ref: "cafebabe", entries: entries, selfID: nil)
        XCTAssertEqual(try? result.get().session.id, id)
    }

    func testHexPrefixFallsThroughToTitleWhenNoUUIDMatches() {
        let entries = [makeEntry(title: "deadbeef-arbeit")]
        let result = SessionRefResolver.resolve(ref: "deadbeef", entries: entries, selfID: nil)
        XCTAssertEqual(try? result.get().session.title, "deadbeef-arbeit")
    }

    func testAmbiguousPrefixFails() {
        let a = UUID(uuidString: "AAAAAAAA-1111-4000-8000-000000000001")!
        let b = UUID(uuidString: "AAAAAAAA-2222-4000-8000-000000000002")!
        let entries = [makeEntry(title: "x", id: a), makeEntry(title: "y", id: b)]
        let result = SessionRefResolver.resolve(ref: "aaaaaaaa", entries: entries, selfID: nil)
        guard case .failure(.ambiguous(_, let candidates)) = result else {
            return XCTFail("Erwartet ambiguous, war \(result)")
        }
        XCTAssertEqual(candidates.count, 2)
    }

    func testProjectSlashTitleDisambiguates() {
        let entries = [
            makeEntry(title: "seo-behandlungsseiten", projectName: "wolanin", projectPath: "/x/wolanin-md"),
            makeEntry(title: "seo-audit-juli", projectName: "rankm8", projectPath: "/x/rankm8"),
        ]
        let global = SessionRefResolver.resolve(ref: "seo", entries: entries, selfID: nil)
        guard case .failure(.ambiguous) = global else {
            return XCTFail("Global muss mehrdeutig sein")
        }
        let scoped = SessionRefResolver.resolve(ref: "wolanin/seo", entries: entries, selfID: nil)
        XCTAssertEqual(try? scoped.get().session.title, "seo-behandlungsseiten")
    }

    func testProjectMatchesLastPathSegment() {
        let entries = [makeEntry(title: "plan", projectName: "Anders Benannt", projectPath: "/repos/whisperm8")]
        let result = SessionRefResolver.resolve(ref: "whisperm8/plan", entries: entries, selfID: nil)
        XCTAssertNotNil(try? result.get())
    }

    func testNormalizationFoldsDiacriticsAndSeparators() {
        let entries = [makeEntry(title: "SEO-Behandlungsseiten für Ärzte")]
        let result = SessionRefResolver.resolve(ref: "behandlungsseiten fur arzte", entries: entries, selfID: nil)
        XCTAssertNotNil(try? result.get())
    }

    func testSubsequenceFallback() {
        let entries = [makeEntry(title: "pill-redesign")]
        let result = SessionRefResolver.resolve(ref: "pillre", entries: entries, selfID: nil)
        XCTAssertNotNil(try? result.get())
    }

    func testGroupNameMatchesWhenTitleMisses() {
        let entries = [makeEntry(title: "run-42", groupName: "creative-batch")]
        let result = SessionRefResolver.resolve(ref: "creative", entries: entries, selfID: nil)
        XCTAssertNotNil(try? result.get())
    }

    func testSelfResolvesViaSelfID() {
        let id = UUID()
        let entries = [makeEntry(title: "ich", id: id), makeEntry(title: "andere")]
        let result = SessionRefResolver.resolve(ref: "@self", entries: entries, selfID: id)
        XCTAssertEqual(try? result.get().session.id, id)
    }

    func testSelfWithoutContextFails() {
        let result = SessionRefResolver.resolve(ref: "@self", entries: [makeEntry(title: "x")], selfID: nil)
        guard case .failure(.noSelfContext) = result else {
            return XCTFail("Erwartet noSelfContext")
        }
    }

    func testArchivedExcludedByDefaultIncludedWithFlag() {
        let entries = [makeEntry(title: "alt", status: .archived)]
        let hidden = SessionRefResolver.resolve(ref: "alt", entries: entries, selfID: nil)
        guard case .failure(.notFound) = hidden else {
            return XCTFail("Archivierte dürfen im Default-Scope nicht auflösen")
        }
        let visible = SessionRefResolver.resolve(ref: "alt", entries: entries, selfID: nil, includeArchived: true)
        XCTAssertNotNil(try? visible.get())
    }

    func testCandidatesSortedByActivityAndCapped() {
        let now = Date()
        let entries = (0..<8).map { i in
            makeEntry(title: "batch-\(i)", lastActivityAt: now.addingTimeInterval(TimeInterval(-i * 60)))
        }
        let result = SessionRefResolver.resolve(ref: "batch", entries: entries, selfID: nil)
        guard case .failure(.ambiguous(_, let candidates)) = result else {
            return XCTFail("Erwartet ambiguous")
        }
        XCTAssertEqual(candidates.count, SessionRefResolver.maxCandidatesInError)
        XCTAssertEqual(candidates.first?.title, "batch-0")
    }
}

// MARK: - ChatsStatusProbe (derive-Kern mit Temp-Transcripts)

final class ChatsStatusProbeTests: XCTestCase {
    private var tempDir: URL!

    override func setUpWithError() throws {
        tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("chats-probe-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
    }

    override func tearDownWithError() throws {
        try? FileManager.default.removeItem(at: tempDir)
    }

    private func writeTranscript(_ lines: [String], mtime: Date? = nil) throws -> URL {
        let url = tempDir.appendingPathComponent("\(UUID().uuidString).jsonl")
        try lines.joined(separator: "\n").appending("\n").write(to: url, atomically: true, encoding: .utf8)
        if let mtime {
            try FileManager.default.setAttributes([.modificationDate: mtime], ofItemAtPath: url.path)
        }
        return url
    }

    private func claudeUserLine(text: String = "mach was") -> String {
        #"{"type":"user","message":{"content":[{"type":"text","text":"\#(text)"}]}}"#
    }

    private func claudeAssistantStopped(reason: String = "end_turn") -> String {
        #"{"type":"assistant","message":{"stop_reason":"\#(reason)","content":[{"type":"text","text":"fertig"}]}}"#
    }

    func testFreshUserMessageIsWorking() throws {
        let now = Date()
        let url = try writeTranscript([claudeUserLine()], mtime: now.addingTimeInterval(-5))
        let session = makeEntry(title: "t").session
        let info = ChatsStatusProbe.derive(from: url, provider: .claude, session: session, source: "transcriptEstimate", now: now)
        XCTAssertEqual(info.status, .working)
        XCTAssertEqual(info.availability, .available)
        XCTAssertEqual(info.revision, info.transcriptSizeBytes)
    }

    func testEndTurnIsIdle() throws {
        let now = Date()
        let url = try writeTranscript([claudeUserLine(), claudeAssistantStopped()], mtime: now.addingTimeInterval(-10))
        let session = makeEntry(title: "t").session
        let info = ChatsStatusProbe.derive(from: url, provider: .claude, session: session, source: "transcriptEstimate", now: now)
        XCTAssertEqual(info.status, .idle)
    }

    func testToolUseStopReasonStaysWorking() throws {
        let now = Date()
        let url = try writeTranscript([claudeAssistantStopped(reason: "tool_use")], mtime: now.addingTimeInterval(-5))
        let session = makeEntry(title: "t").session
        let info = ChatsStatusProbe.derive(from: url, provider: .claude, session: session, source: "transcriptEstimate", now: now)
        XCTAssertEqual(info.status, .working)
    }

    func testStalledWorkDowngradesToIdleAfterThreshold() throws {
        let now = Date()
        let staleMtime = now.addingTimeInterval(-(AgentTranscriptStatusDecider.workingStallSeconds + 10))
        let url = try writeTranscript([claudeUserLine()], mtime: staleMtime)
        let session = makeEntry(title: "t").session
        let info = ChatsStatusProbe.derive(from: url, provider: .claude, session: session, source: "transcriptEstimate", now: now)
        XCTAssertEqual(info.status, .idle)
    }

    func testClosedQuietSessionReportsStopped() throws {
        let now = Date()
        let staleMtime = now.addingTimeInterval(-(ChatsStatusProbe.closedQuietSeconds + 60))
        let url = try writeTranscript([claudeUserLine(), claudeAssistantStopped()], mtime: staleMtime)
        let session = makeEntry(title: "t", status: .closed).session
        let info = ChatsStatusProbe.derive(from: url, provider: .claude, session: session, source: "transcriptEstimate", now: now)
        XCTAssertEqual(info.status, .stopped)
    }

    func testRecentlyActiveClosedSessionKeepsDeciderStatus() throws {
        let now = Date()
        let url = try writeTranscript([claudeUserLine(), claudeAssistantStopped()], mtime: now.addingTimeInterval(-40))
        let session = makeEntry(title: "t", status: .closed).session
        let info = ChatsStatusProbe.derive(from: url, provider: .claude, session: session, source: "transcriptEstimate", now: now)
        XCTAssertEqual(info.status, .idle)
    }

    func testMissingTranscriptEntryYieldsAvailabilityMarker() {
        let entry = makeEntry(title: "frisch")  // ohne externalSessionID
        let info = ChatsStatusProbe.probe(entry: entry)
        XCTAssertNil(info.status)
        XCTAssertEqual(info.availability, .missingExternalSessionID)
    }

    func testUnsupportedKinds() {
        let terminal = makeEntry(title: "term", kind: .terminal)
        XCTAssertEqual(ChatsStatusProbe.probe(entry: terminal).availability, .unsupported)
        let agentView = makeEntry(title: "view", kind: .agentView)
        XCTAssertEqual(ChatsStatusProbe.probe(entry: agentView).availability, .unsupported)
    }
}

// MARK: - AttentionModelBuilder

final class AttentionModelBuilderTests: XCTestCase {
    private func runtime(_ status: AgentSessionRuntimeStatus?, since: Date? = nil) -> ChatsRuntimeInfo {
        ChatsRuntimeInfo(status: status, source: "transcriptEstimate", since: since,
                         revision: 1, transcriptPath: nil, transcriptSizeBytes: 1,
                         availability: .available)
    }

    func testOrderingAcrossCategories() {
        let now = Date()
        let items: [(entry: ChatsSessionEntry, runtime: ChatsRuntimeInfo)] = [
            (makeEntry(title: "arbeitet"), runtime(.working, since: now)),
            (makeEntry(title: "idle-alt"), runtime(.idle, since: now.addingTimeInterval(-3600))),
            (makeEntry(title: "wartet"), runtime(.awaitingInput, since: now)),
            (makeEntry(title: "kaputt"), runtime(.errored, since: now)),
            (makeEntry(title: "frisch", lastTurnAt: now.addingTimeInterval(-60)), runtime(.idle, since: now.addingTimeInterval(-60))),
        ]
        let board = AttentionModelBuilder.build(items: items, now: now)
        XCTAssertEqual(board.items.map(\.entry.session.title),
                       ["wartet", "kaputt", "frisch", "arbeitet", "idle-alt"])
        XCTAssertEqual(board.counts[.needsYou], 2)
        XCTAssertEqual(board.counts[.freshDone], 1)
        XCTAssertEqual(board.counts[.working], 1)
        XCTAssertEqual(board.counts[.idle], 1)
    }

    func testFreshDoneWindowExpires() {
        let now = Date()
        let justOver = now.addingTimeInterval(-(AttentionModelBuilder.freshDoneWindow + 30))
        let items: [(entry: ChatsSessionEntry, runtime: ChatsRuntimeInfo)] = [
            (makeEntry(title: "abgelaufen", lastTurnAt: justOver), runtime(.idle, since: justOver)),
        ]
        let board = AttentionModelBuilder.build(items: items, now: now)
        XCTAssertEqual(board.items.first?.category, .idle)
    }

    func testWithinRankNewestFirst() {
        let now = Date()
        let items: [(entry: ChatsSessionEntry, runtime: ChatsRuntimeInfo)] = [
            (makeEntry(title: "alt"), runtime(.working, since: now.addingTimeInterval(-600))),
            (makeEntry(title: "neu"), runtime(.working, since: now.addingTimeInterval(-30))),
        ]
        let board = AttentionModelBuilder.build(items: items, now: now)
        XCTAssertEqual(board.items.map(\.entry.session.title), ["neu", "alt"])
    }
}

// MARK: - ChatsTailFormatter

final class ChatsTailFormatterTests: XCTestCase {
    private func message(_ role: AgentChatMessage.Role, _ blocks: [AgentChatBlock]) -> AgentChatMessage {
        AgentChatMessage(id: UUID(), role: role, timestamp: nil, blocks: blocks)
    }

    func testTurnGroupingKeepsLastNTurns() {
        let transcript = AgentChatTranscript(messages: [
            message(.user, [.text("frage 1")]),
            message(.assistant, [.text("antwort 1")]),
            message(.user, [.text("frage 2")]),
            message(.assistant, [.text("antwort 2")]),
            message(.user, [.text("frage 3")]),
            message(.assistant, [.text("antwort 3")]),
        ], isLiveSourcePossible: false)
        let rendered = ChatsTailFormatter.render(transcript: transcript, turns: 2, maxChars: 10_000)
        XCTAssertFalse(rendered.text.contains("frage 1"))
        XCTAssertTrue(rendered.text.contains("frage 2"))
        XCTAssertTrue(rendered.text.contains("antwort 3"))
        XCTAssertEqual(rendered.turnCount, 2)
    }

    func testToolUseRenderedAsOneLinerThinkingSkipped() {
        let transcript = AgentChatTranscript(messages: [
            message(.user, [.text("los")]),
            message(.assistant, [
                .thinking("geheime gedanken"),
                .toolUse(name: "Bash", input: "swift test\n--filter Foo"),
                .text("erledigt"),
            ]),
        ], isLiveSourcePossible: false)
        let rendered = ChatsTailFormatter.render(transcript: transcript)
        XCTAssertTrue(rendered.text.contains("⏺ Bash: swift test --filter Foo"))
        XCTAssertFalse(rendered.text.contains("geheime gedanken"))
    }

    func testToolResultOnlyShownOnError() {
        let transcript = AgentChatTranscript(messages: [
            message(.user, [.text("los")]),
            message(.user, [.toolResult(content: "alles ok", isError: false)]),
            message(.user, [.toolResult(content: "kaboom", isError: true)]),
        ], isLiveSourcePossible: false)
        let rendered = ChatsTailFormatter.render(transcript: transcript)
        XCTAssertFalse(rendered.text.contains("alles ok"))
        XCTAssertTrue(rendered.text.contains("⚠︎ tool error: kaboom"))
    }

    func testCharCapTrimsFromFront() {
        let longText = String(repeating: "x", count: 500)
        let transcript = AgentChatTranscript(messages: [
            message(.user, [.text(longText)]),
            message(.assistant, [.text("SCHLUSS")]),
        ], isLiveSourcePossible: false)
        let rendered = ChatsTailFormatter.render(transcript: transcript, turns: 3, maxChars: 120)
        XCTAssertTrue(rendered.wasTruncated)
        XCTAssertTrue(rendered.text.hasPrefix("… [gekürzt]"))
        XCTAssertTrue(rendered.text.contains("SCHLUSS"))
        XCTAssertLessThan(rendered.text.count, 200)
    }

    func testLastAssistantLineFlattensAndCaps() {
        let transcript = AgentChatTranscript(messages: [
            message(.assistant, [.text("Zeile eins\nZeile zwei mit sehr viel Inhalt der weit über achtzig Zeichen hinausgehen sollte, versprochen")]),
        ], isLiveSourcePossible: false)
        let line = ChatsTailFormatter.lastAssistantLine(transcript: transcript, maxChars: 40)
        XCTAssertNotNil(line)
        XCTAssertLessThanOrEqual(line!.count, 40)
        XCTAssertFalse(line!.contains("\n"))
        XCTAssertTrue(line!.hasSuffix("…"))
    }
}

// MARK: - Parser + Workspace-Reader

final class ChatsCLIParserTests: XCTestCase {
    func testParseListDefaultsAndFlags() throws {
        XCTAssertEqual(try ChatsCLIParser.parseList([]), ChatsListOptions())
        let parsed = try ChatsCLIParser.parseList(
            ["--project", "whisperm8", "--status", "working", "--attention", "--all",
             "--sort", "attention", "--format", "board", "--json"])
        XCTAssertEqual(parsed.project, "whisperm8")
        XCTAssertEqual(parsed.status, "working")
        XCTAssertTrue(parsed.attentionOnly && parsed.all && parsed.json)
        XCTAssertEqual(parsed.sort, "attention")
        XCTAssertEqual(parsed.format, "board")
    }

    func testParseListRejectsBadStatusAndUnknownFlag() {
        XCTAssertThrowsError(try ChatsCLIParser.parseList(["--status", "banane"]))
        XCTAssertThrowsError(try ChatsCLIParser.parseList(["--frobnicate"]))
        XCTAssertThrowsError(try ChatsCLIParser.parseList(["--project"]))
    }

    func testParseCloseAcceptsMultipleRefsAndJSON() throws {
        let single = try ChatsCLIParser.parseClose(["whisperm8/audit"])
        XCTAssertEqual(single.refs, ["whisperm8/audit"])
        XCTAssertFalse(single.json)

        let batch = try ChatsCLIParser.parseClose(["a", "b/c", "--json", "d"])
        XCTAssertEqual(batch.refs, ["a", "b/c", "d"], "Refs bleiben in Angabe-Reihenfolge")
        XCTAssertTrue(batch.json)
    }

    func testParseCloseRejectsEmptyAndUnknownFlags() {
        XCTAssertThrowsError(try ChatsCLIParser.parseClose([]))
        XCTAssertThrowsError(try ChatsCLIParser.parseClose(["--json"]), "nur Flags, keine Refs")
        XCTAssertThrowsError(try ChatsCLIParser.parseClose(["ref", "--all"]),
                             "kein pauschaler --all-Pfad — Kandidaten waehlt der Aufrufer explizit")
        XCTAssertThrowsError(try ChatsCLIParser.parseClose(["ref", "--force"]),
                             "close kennt kein --force: es gibt nichts zu erzwingen")
    }

    func testParseShowAndTailRequireExactlyOneRef() {
        XCTAssertThrowsError(try ChatsCLIParser.parseShow([]))
        XCTAssertThrowsError(try ChatsCLIParser.parseShow(["a", "b"]))
        XCTAssertEqual(try ChatsCLIParser.parseShow(["wolanin/seo", "--json"]).ref, "wolanin/seo")

        XCTAssertThrowsError(try ChatsCLIParser.parseTail([]))
        let tail = try? ChatsCLIParser.parseTail(["x", "--turns", "5", "--chars", "1000", "--raw"])
        XCTAssertEqual(tail?.turns, 5)
        XCTAssertEqual(tail?.chars, 1000)
        XCTAssertEqual(tail?.raw, true)
        XCTAssertThrowsError(try ChatsCLIParser.parseTail(["x", "--turns", "0"]))
    }
}

final class ChatsWorkspaceReaderTests: XCTestCase {
    func testUIStateReadHasNoWriteSideEffect() throws {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("chats-reader-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: dir) }

        let workspaceURL = dir.appendingPathComponent("AgentSessions.json")
        let uiStateURL = dir.appendingPathComponent("agent-ui-state.json")

        let project = AgentProject(name: "demo", path: "/tmp/demo")
        let session = AgentChatSession(provider: .claude, projectID: project.id, title: "test-session")
        let workspace = AgentWorkspace(projects: [project], sessions: [session])
        try AgentWorkspaceRepository(fileURL: workspaceURL).save(workspace)

        // Minimaler v4-UI-State direkt als JSON.
        let uiState = AgentUIState.empty
        let data = try JSONEncoder().encode(uiState)
        try data.write(to: uiStateURL)
        let mtimeBefore = try FileManager.default.attributesOfItem(atPath: uiStateURL.path)[.modificationDate] as? Date

        let view = ChatsWorkspaceReader(workspaceFileURL: workspaceURL, uiStateFileURL: uiStateURL).load()
        XCTAssertEqual(view.entries.count, 1)
        XCTAssertEqual(view.entries.first?.projectName, "demo")
        XCTAssertNotNil(view.uiState)

        let mtimeAfter = try FileManager.default.attributesOfItem(atPath: uiStateURL.path)[.modificationDate] as? Date
        XCTAssertEqual(mtimeBefore, mtimeAfter, "UI-State-Read darf nie schreiben")
    }

    func testOpenTabsAndPinsExtractedFromUIState() throws {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("chats-reader-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: dir) }
        let workspaceURL = dir.appendingPathComponent("AgentSessions.json")
        let uiStateURL = dir.appendingPathComponent("agent-ui-state.json")

        let project = AgentProject(name: "demo", path: "/tmp/demo")
        let openInWindow = AgentChatSession(provider: .claude, projectID: project.id, title: "offen-fenster")
        let openGlobal = AgentChatSession(provider: .claude, projectID: project.id, title: "offen-global")
        let pinned = AgentChatSession(provider: .claude, projectID: project.id, title: "gepinnt")
        let plain = AgentChatSession(provider: .claude, projectID: project.id, title: "normal")
        try AgentWorkspaceRepository(fileURL: workspaceURL).save(
            AgentWorkspace(projects: [project], sessions: [openInWindow, openGlobal, pinned, plain]))

        var uiState = AgentUIState.empty
        uiState.openTabIDs = [openGlobal.id]
        uiState.pinnedSessionIDs = [pinned.id]
        var window = uiState.windows.first ?? AgentChatWindowState(id: UUID(), isPrimary: true)
        window.openTabIDs = [openInWindow.id]
        uiState.windows = [window]
        try JSONEncoder().encode(uiState).write(to: uiStateURL)

        let view = ChatsWorkspaceReader(workspaceFileURL: workspaceURL, uiStateFileURL: uiStateURL).load()
        // Offene Tabs = Vereinigung aus globaler Liste UND allen Fenstern.
        XCTAssertTrue(view.openTabIDs.contains(openGlobal.id))
        XCTAssertTrue(view.openTabIDs.contains(openInWindow.id))
        XCTAssertFalse(view.openTabIDs.contains(plain.id))
        XCTAssertEqual(view.pinnedSessionIDs, [pinned.id])
    }

    func testSessionsWithoutProjectAreDropped() throws {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("chats-reader-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: dir) }
        let workspaceURL = dir.appendingPathComponent("AgentSessions.json")
        let orphan = AgentChatSession(provider: .codex, projectID: UUID(), title: "verwaist")
        try AgentWorkspaceRepository(fileURL: workspaceURL).save(AgentWorkspace(projects: [], sessions: [orphan]))
        let view = ChatsWorkspaceReader(
            workspaceFileURL: workspaceURL,
            uiStateFileURL: dir.appendingPathComponent("missing.json")
        ).load()
        XCTAssertTrue(view.entries.isEmpty)
        XCTAssertNil(view.uiState)
    }
}
